Feature/openstack
cloudbase/arestor pull request #2
Opened 2017-04-21 02:02 UTC by micumatei

2017-04-28 08:53 UTC, ader1990 requested changes

2017-04-28 08:53 UTC, ader1990 commented on arestor/api/__init__.py
>                  'server.thread_pool': CONFIG.api.thread_pool,
being an API change, this should have a commit message that presents the changes

2017-04-28 08:54 UTC, ader1990 requested changes
plus add a more informational commit message

2017-04-28 08:54 UTC, ader1990 commented on arestor/common/tools.py
> +            LOG.error("Malformated signature provided.")
Malformed*

2017-04-28 08:55 UTC, ader1990 requested changes
add a better commit message

2017-04-28 09:14 UTC, ader1990 requested changes
Add a better commit message

2017-04-28 11:24 UTC, paulaCrismaru requested changes

2017-04-28 11:24 UTC, paulaCrismaru commented on arestor/api/admin/resource.py
> +        if not any([resource_id, namespace, client_id, resource]):
unnecessary. same result as L61-L68

2017-04-28 11:24 UTC, paulaCrismaru commented on arestor/api/v1/openstack.py
> +        data = None
Should it be None or empty string?

2017-04-28 11:24 UTC, paulaCrismaru commented on arestor/api/v1/openstack.py
> +        data = None
same

2017-04-28 11:24 UTC, paulaCrismaru commented on arestor/api/v1/openstack.py
> +    """Containe for all the resources from the legacy version of the API."""
Container*

2017-04-28 11:24 UTC, paulaCrismaru commented on arestor/client/arestor_client.py
> +        url = self._base_url + "/v1/" + self._client_id + "/" + self._namespace
you should use  url_parse.urljoin

2017-04-28 11:35 UTC, ader1990 requested changes

2017-04-28 11:35 UTC, ader1990 commented on arestor/api/admin/__init__.py
> +# Copyright 2016 Cloudbase Solutions Srl
2017*

2017-04-28 11:35 UTC, ader1990 commented on arestor/api/admin/resource.py
> +# Copyright 2016 Cloudbase Solutions Srl
ditto

2017-04-28 11:35 UTC, ader1990 commented on arestor/api/__init__.py
>  import cherrypy
add a commit description

2017-04-28 11:38 UTC, ader1990 requested changes

2017-04-28 11:38 UTC, ader1990 commented on arestor/client/__init__.py
> +# Copyright 2016 Cloudbase Solutions Srl
ditto

2017-04-28 11:38 UTC, ader1990 commented on arestor/client/base.py
> +# Copyright 2016 Cloudbase Solutions Srl
ditto

2017-04-28 11:38 UTC, ader1990 commented on arestor/client/base.py
> +        """View the required resource."""
Get the required*

2017-04-28 11:38 UTC, ader1990 commented on arestor/client/base.py
> +    def _get_parameters(self):
_get_auth_params -- name the methods according to what they do

2017-04-28 11:38 UTC, ader1990 commented on arestor/common/exception.py
> +    """Something went wrong during communication with the API."""
This should describe the class, and not be an error message.

2017-04-28 11:38 UTC, ader1990 commented on arestor/common/exception.py
> +    template = ("Something went wrong during "
Failed to communicate with the Arestor API.

2017-04-28 11:40 UTC, ader1990 requested changes

2017-04-28 11:40 UTC, ader1990 commented on arestor/client/resource.py
> +# Copyright 2016 Cloudbase Solutions Srl
ditto

2017-04-28 11:40 UTC, ader1990 commented on arestor/client/resource.py
> +        """Update the content of the required resource."""
of the given*

2017-04-28 11:40 UTC, ader1990 commented on arestor/client/resource.py
> +        """Delete the required resource."""
the given*

2017-04-28 11:40 UTC, ader1990 commented on arestor/client/resource.py
> +# Copyright 2016 Cloudbase Solutions Srl
add a description for the commit

2017-04-28 11:41 UTC, ader1990 requested changes

2017-04-28 11:41 UTC, ader1990 commented on arestor/client/arestor_client.py
> +# Copyright 2016 Cloudbase Solutions Srl
ditto1

2017-04-28 11:41 UTC, ader1990 commented on arestor/client/arestor_client.py
> +# Copyright 2016 Cloudbase Solutions Srl
ditto2 (add a better description to what you commited)

2017-04-28 11:41 UTC, ader1990 commented on arestor/client/arestor_client.py
> +        """Delete all meta_data for this client_id."""
for the current client_id

2017-04-28 11:42 UTC, ader1990 requested changes

2017-04-28 11:42 UTC, ader1990 commented on arestor/api/v1/openstack.py
> +        # this could be emply
empty*

2017-04-28 11:43 UTC, ader1990 requested changes

2017-04-28 11:43 UTC, ader1990 commented on arestor/api/v1/openstack.py
>  #    under the License.
ditto2

2017-04-28 11:43 UTC, ader1990 approved these changes

2017-05-02 17:18 UTC, micumatei commented on arestor/api/__init__.py
>  import cherrypy
Done

2017-05-02 17:20 UTC, micumatei commented on arestor/api/v1/openstack.py
> +        data = None
This is a good question. Where is no date do we give an empty string or say it's `None`.

2017-05-03 13:36 UTC, micumatei commented on arestor/api/__init__.py
>                  'server.thread_pool': CONFIG.api.thread_pool,
Done

2017-05-03 16:51 UTC, ader1990 approved these changes

2017-05-03 16:51 UTC, ader1990 commented on arestor/api/__init__.py
>  import cherrypy
can't see it

2017-05-03 16:54 UTC, merged